server:
  port: 8088
  
spring :
  #### DB
  datasource : 
    driver-class-name : org.mariadb.jdbc.Driver
    url : 
    username : 
    password : 
  
  ### 내용 갱신 시 서버 reloading
  devtools :
    livereload :
      enabled : true
      
  ### view page
  mvc : 
    view :
      prefix : /views/
      suffix : .jsp
      
###mybatis 설정

mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: aaa.model/**